language: csharp
mono: none
dotnet: 3.1.201
before_script: cd backend/DIMU
script:
- dotnet restore
- dotnet build
deploy:
  app: dimu-backend
  api_key:
    secure: hNbLngEgsxZVI9foYeEcnmqvvEmhp1RgNfjabyWyv2Di7G+uKMzc0kzRKFDLOLsDz4SPNttYdXaatD/hn5b74KIv98qUhH39I8CyiyglelVD+2OIneRN2B4+/s9XhS49FeK17dOqXGY3bNQTqBrlCo99X8AGINUANqMqJ0VnTFHkAzhc4j858FB8uBPlPhJNz9yPnZq0yc8aGME90dCwglMryJCv8zn7uhaEx+PHRLCF7pikvGSgtIKgQWbAHd1x2nfcv5StKsaicWBKmFXYirg2vJQYt883HRjIiv2bJDagYwxf7uAU3oI45FuV48pjN+V7qRbzXuWKcNyOdKJnyjjg/e183N7XsBsdS3giERe9PuznrVxAsSnVkwun8nQB9+nTZFRs46K/3aPz+IeXeFRWxHkm+BD4jr+/oN3vpTdGiiWvnTLxRWTGLEpM7gDIKDwPTnw/AvC3kV5Va/bBh0OrN66lBrdcgJ6XDEhqYqFcvzvpncLjxAaDrG6tvWgPMy8e7NoFMlx7kn0nHqvgN7g151Vn8jwvELkihD1xVLtNjKDlhwnUl+AEq8jP2juQ1xuYW/rZcMXwCWfMbumKCkV7ETCHSrkkmJtLzfiSUskm7TG0UsO4UFatzhy9ErpDIIBSYtXOEJjbXa4HpRKmXhaYaGk4oGttzFyS9O2gQ+w=
